In [1]:
import numpy as np

In [2]:
arr = np.array([1, 4, 5, 6, 7, 7, 8]) #1D array
print(arr)

[1 4 5 6 7 7 8]


In [3]:
arr = np.array([[1, 3, 4], [5, 6, 1], [4, 5, 6]])
print(arr)

[[1 3 4]
 [5 6 1]
 [4 5 6]]


In [7]:
arr = np.array([[1, 3, 4], [5, 6, 1], [4, 5, 6]])
print(arr)
print(arr.sum())
print(arr.sum(axis= 0)) #this sums up the array column wise
print(arr.sum(axis= 1)) #this sums up the array row wise

[[1 3 4]
 [5 6 1]
 [4 5 6]]
35
[10 14 11]
[ 8 12 15]


In [8]:
arr = np.array([[1, 3, 4], [5, 6, 1], [4, 5, 6]])
print(arr)
print(f"The average of whole array is : {np.average(arr)}")
print(f"The average of array column wise is : {np.average(arr, axis = 0)}")
print(f"The average of array row wise is : {np.average(arr, axis = 1)}")

[[1 3 4]
 [5 6 1]
 [4 5 6]]
The average of whole array is : 3.888888888888889
The average of array column wise is : [3.33333333 4.66666667 3.66666667]
The average of array row wise is : [2.66666667 4.         5.        ]


In [10]:
arr = np.array([[1, 3, 4], [5, 6, 1], [4, 5, 6]])
print(arr)
print(f"The prod of whole array is : {np.prod(arr)}")
print(f"The prod of array column wise is : {np.prod(arr, axis = 0)}")
print(f"The prod of array row wise is : {np.prod(arr, axis = 1)}")

[[1 3 4]
 [5 6 1]
 [4 5 6]]
The prod of whole array is : 43200
The prod of array column wise is : [20 90 24]
The prod of array row wise is : [ 12  30 120]


In [14]:
arr = np.array([[1, 3, 4], [5, 6, 1], [4, 5, 6]])
print(arr)
print(f"The min of whole array is : {np.min(arr)}")
print(f"The min of array column wise is : {np.min(arr, axis = 0)}")
print(f"The min of array row wise is : {np.min(arr, axis = 1)}")

[[1 3 4]
 [5 6 1]
 [4 5 6]]
The min of whole array is : 1
The min of array column wise is : [1 3 1]
The min of array row wise is : [1 1 4]


In [12]:
arr = np.array([[1, 3, 4], [5, 6, 1], [4, 5, 6]])
print(arr)
print(f"The max of whole array is : {np.max(arr)}")
print(f"The max of array column wise is : {np.max(arr, axis = 0)}")
print(f"The max of array row wise is : {np.max(arr, axis = 1)}")

[[1 3 4]
 [5 6 1]
 [4 5 6]]
The max of whole array is : 6
The max of array column wise is : [5 6 6]
The max of array row wise is : [4 6 6]


In [17]:
arr1 = np.array([[1, 3, 4], [5, 6, 1], [4, 5, 6]])
arr2 = np.array([[4, 3, 2], [1, 5, 7], [7, 8,1]])
print(arr1)
print(arr2)
print(f"The minimum of 2 array is : \n{np.minimum(arr1,arr2)}")

[[1 3 4]
 [5 6 1]
 [4 5 6]]
[[4 3 2]
 [1 5 7]
 [7 8 1]]
The minimum of 2 array is : 
[[1 3 2]
 [1 5 1]
 [4 5 1]]


In [24]:
arr1 = np.array([[1, 3, 4], [5, 6, 1], [4, 5, 6]])
arr2 = np.array([[4, 3, 2], [1, 5, 7], [7, 8,1]])
print(arr1)
print(arr2)
print(f"The maximum of 2 array is : \n{np.maximum(arr1,arr2)}")

[[1 3 4]
 [5 6 1]
 [4 5 6]]
[[4 3 2]
 [1 5 7]
 [7 8 1]]
The maximum of 2 array is : 
[[4 3 4]
 [5 6 7]
 [7 8 6]]


Median

In [29]:
list1 = [ 1, 4, 2, 0, 5, 6, 55, 44, 45, 67, 23, 78]
list1.sort()
print(len(list1))
arr1 = np.array(list1)
print(arr1)
print(f"The median of the array is : {np.median(arr1)}")

12
[ 0  1  2  4  5  6 23 44 45 55 67 78]
The median of the array is : 14.5


Arithmetic Operations

In [32]:
arr1 = np.array([[1, 3, 4], [5, 6, 1], [4, 5, 6]])
arr2 = np.array([[4, 3, 2], [1, 5, 7], [7, 8,1]])
print(f"The sum of 2 array is : {np.add(arr1, arr2)}")
print(f"The difference of 2 array is : {np.subtract(arr1, arr2)}")
print(f"The multiplication of 2 array is : {np.multiply(arr1, arr2)}")
print(f"The division of 2 array is : {np.divide(arr1, arr2)}")
print(f"The mod of 2 array is : {np.mod(arr1, arr2)}")
print(f"The remainder of 2 array is : {np.remainder(arr1, arr2)}")

The sum of 2 array is : [[ 5  6  6]
 [ 6 11  8]
 [11 13  7]]
The difference of 2 array is : [[-3  0  2]
 [ 4  1 -6]
 [-3 -3  5]]
The multiplication of 2 array is : [[ 4  9  8]
 [ 5 30  7]
 [28 40  6]]
The division of 2 array is : [[0.25       1.         2.        ]
 [5.         1.2        0.14285714]
 [0.57142857 0.625      6.        ]]
The mod of 2 array is : [[1 0 0]
 [0 1 1]
 [4 5 0]]
The remainder of 2 array is : [[1 0 0]
 [0 1 1]
 [4 5 0]]


Comparision Operators

In [35]:
arr1 = np.array([[1, 3, 4], [5, 6, 1], [4, 5, 6]])
arr2 = np.array([[4, 3, 2], [1, 5, 7], [7, 8,1]])
#print(arr1)
#print(arr2)
print(f"Checking for greater() : \n {np.greater(arr1,arr2)}")
print(f"Checking for greater_equal() : \n {np.greater_equal(arr1,arr2)}")
print(f"Checking for less() : \n {np.less(arr1,arr2)}")
print(f"Checking for less_equal() : \n {np.less_equal(arr1,arr2)}")
print(f"Checking for equal() : \n {np.equal(arr1,arr2)}")
print(f"Checking for not_equal() : \n {np.not_equal(arr1,arr2)}")

Checking for greater() : 
 [[False False  True]
 [ True  True False]
 [False False  True]]
Checking for greater_equal() : 
 [[False  True  True]
 [ True  True False]
 [False False  True]]
Checking for less() : 
 [[ True False False]
 [False False  True]
 [ True  True False]]
Checking for less_equal() : 
 [[ True  True False]
 [False False  True]
 [ True  True False]]
Checking for equal() : 
 [[False  True False]
 [False False False]
 [False False False]]
Checking for not_equal() : 
 [[ True False  True]
 [ True  True  True]
 [ True  True  True]]


In [36]:
arr1 = np.array([[1, 3, 4], [5, 6, 1], [4, 5, 6]])
arr2 = np.array([[4, 3, 2], [1, 5, 7], [7, 8,1]])
#print(arr1)
#print(arr2)
print(f"Checking for > : \n {arr1 > arr2}")
print(f"Checking for >= : \n {arr1 >= arr2}")
print(f"Checking for < : \n {arr1 < arr2}")
print(f"Checking for <= : \n {arr1 <= arr2}")
print(f"Checking for == : \n {arr1 == arr2}")
print(f"Checking for != : \n {arr1 != arr2}")


Checking for > : 
 [[False False  True]
 [ True  True False]
 [False False  True]]
Checking for >= : 
 [[False  True  True]
 [ True  True False]
 [False False  True]]
Checking for < : 
 [[ True False False]
 [False False  True]
 [ True  True False]]
Checking for <= : 
 [[ True  True False]
 [False False  True]
 [ True  True False]]
Checking for == : 
 [[False  True False]
 [False False False]
 [False False False]]
Checking for != : 
 [[ True False  True]
 [ True  True  True]
 [ True  True  True]]


In [39]:
arr1 = np.array([[1, 3, 4], [5, 6, 1], [4, 5, 6]])
arr2 = np.array([[4, 3, 2], [1, 5, 7], [7, 8,1]])
#print(arr1)
#print(arr2)
print(f"Checking for != : \n {arr1 != arr2}")
print(f"Checking for all true : \n {np.alltrue(arr1 != arr2)}")
print(f"Checking for some true : \n {np.sometrue(arr1 != arr2)}")


Checking for != : 
 [[ True False  True]
 [ True  True  True]
 [ True  True  True]]
Checking for all true : 
 False
Checking for some true : 
 True


random values

In [43]:
arr = np.random.rand(7) #this will generate 7 random values between 0 and 1
print(arr)

[0.51228184 0.8091434  0.3635577  0.59042966 0.90568352 0.84421085
 0.69597524]


In [48]:
arr = np.random.rand(3,3) #this will generate a 3x3 matric of random values between 0 and 1
print(arr)

[[0.61471228 0.87925069 0.78527778]
 [0.92950087 0.79587691 0.66270432]
 [0.95262934 0.91577291 0.78392574]]


In [50]:
arr = np.random.random((3,3)) #this will generate a 3x3 matric of random values between 0 and 1
print(arr)

[[0.0269909  0.40679414 0.74093739]
 [0.7274721  0.50886131 0.54487064]
 [0.00246009 0.29307866 0.40822321]]


In [69]:
arr = np.random.randint(10, 20, size = (4,4))
print(arr)

[[16 19 16 13]
 [17 16 17 10]
 [11 14 13 12]
 [13 19 10 12]]


In [71]:
arr = np.random.uniform(size = 7)
print(arr)

[0.24506278 0.53714718 0.91920343 0.84695411 0.96874793 0.27762044
 0.29015137]


In [74]:
arr = np.random.randint(10, 20, size = (4,5))
print(arr)
print(np.shape(arr))

[[19 19 11 17 12]
 [10 15 14 17 14]
 [13 18 17 13 14]
 [18 15 16 12 10]]
(4, 5)


In [82]:
print(arr.reshape(1,20))

[[19 19 11 17 12 10 15 14 17 14 13 18 17 13 14 18 15 16 12 10]]


In [85]:
print(np.resize(arr, (5,5)))

[[19 19 11 17 12]
 [10 15 14 17 14]
 [13 18 17 13 14]
 [18 15 16 12 10]
 [19 19 11 17 12]]


In [87]:
print(arr)
print(np.transpose(arr))

[[19 19 11 17 12]
 [10 15 14 17 14]
 [13 18 17 13 14]
 [18 15 16 12 10]]
[[19 10 13 18]
 [19 15 18 15]
 [11 14 17 16]
 [17 17 13 12]
 [12 14 14 10]]


In [88]:
print(arr)
print(arr.flatten())

[[19 19 11 17 12]
 [10 15 14 17 14]
 [13 18 17 13 14]
 [18 15 16 12 10]]
[19 19 11 17 12 10 15 14 17 14 13 18 17 13 14 18 15 16 12 10]


In [92]:
arr1 = np.array([[1, 3, 4], [5, 6, 1], [4, 5, 6]])
arr2 = np.array([[4, 3, 2], [1, 5, 7], [7, 8,1]])
print(np.concatenate((arr1,arr2), axis = 0))

[[1 3 4]
 [5 6 1]
 [4 5 6]
 [4 3 2]
 [1 5 7]
 [7 8 1]]
